### ISSUE TITLE
Listening Post Missions - not triggering journals properly.

### ISSUE THREAD

**Issue by Kinkojiro** [henbagle/LE1CommunityPatch#105]
**Describe the bug**
There are 3 missions post Noveria that relate to Cerberus and the Rachni:
1) Listening Post Alpha
2) Listening Post Theta
3) Depot Sigma 23

Missions 1) and 2) should be done in any order before 3).
There are multiple errors for journaling not triggering:

**Bug A)** On completing the main part of Listening Post Alpha Lieutenant Durand tells you about another Listening Post that has a distress call if you haven't completed Theta.  Otherwise it unlocks Depot Sigma.
However the journal transition is not triggered in the conversation.
There are 2 plot items in the journal
Bool 5868 LPTheta.Begin_Plot_General
Bool 5869 LPTheta.Begin_Plot_from_Alpha
The journal for 5869 should be triggered by transition 4295 but it isn't triggered anywhere.
Bool 5868 is set by transition 4294 which also doesn't seem to trigger anywhere.  Probably should be if the Alliance base is found first and 5869 is not true.

**Bug B)**  On completion of LPTheta you get a terminal and your squadmates explain that a supply ship recently came here.
If the player selects the neutral option then the dialogue checks conditional 1237 (both Alpha + Theta done) and if so gives Depot Sigma.  However if the player chooses the Positive or Negative lines, it skips this check.  As a result Sigma is not unlocked.

Bug A) can be fixed in BIOA_UNC73_01_DSG_LOC_INT  Adding transition 4295 to Entry6 in sp105_marieDurand_dlg
Bug B) can be fixed in BIOA_UNC24_02_DSG_LOC_INT by removing the skips.

Note : it looks like the Galaxy Map also doesn't trigger on 5869 correctly.

**Comment by henbagle** [comment]
Bug A fixed as you described for all localizations, and B fixed in #106.

Fixed another small journal issue that I believe is worth fixing. If you travel to Altahe having completed neither Listening Post mission, you will not be given a journal entry for Listening Post Theta until you actually activate the terminal at the end of the mission, at which point it will be marked as completed. To fix this, I added a large BioTrigger outside the base (around the Rachni nests) that triggers a transition to give you the quest (Transition 4294, Set_Begin_Plot_General true) if you do not already have it. 

The following sequencing (and BioTrigger) added to BIOA_UNC24_01_DSG.pcc 
![image](https://user-images.githubusercontent.com/8151477/144771907-27ec22e8-9e08-4f8a-92be-789bbebf5a8c.png)

**Comment by henbagle** [comment]
An additional bug fixed. Main journal text does not update if you complete Listening Post Alpha and are then given Listening Post Theta by Lt Durand, it is instead stuck complete with the in progress journal text. 

![image](https://user-images.githubusercontent.com/8151477/208768366-b47426ef-7ccc-4bbb-ae25-268228d348cd.png)

Fixed by copying quest 9286 to the LE1CP PlotManager file and altering the order of the Quest goals, so the in-progress goal does not take priority over the quest completed goal. First goal is the in progress goal, second goal is now the goal for when quest completed and LP Theta is given by Durand, third goal is quest completed and LP Theta already completed.

![image](https://user-images.githubusercontent.com/8151477/208768649-d510711e-2eb0-4003-9083-c2265d5db824.png)
