### ISSUE TITLE
Eden Prime: Warren and Manuel conversation lights

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#119]
**Describe the bug**
If you approach Warren and Manuel the second time after exiting the shed they're in, the trigger that initiates the conversation with the two when you walk into the shed for the first time enables the conversation lights before you even talk to them. The lights are never turned off unless you talk to Warren.

After talking to Manuel, the conversation lights are never turned off unless you talk to Warren.

**To Reproduce**
Conversation lights triggered by the trigger
1. Enter the shed with Warren and Manuel for the first time
2. Leave the shed
3. Enter the shed again

Conversation lights not turning off after speaking to Manuel
1. Talk to Warren and exit the conversation to disable the lights
2. Talk with Manuel and exit the conversation

**Expected behavior**
Conversation lights only turning on when talking with the two and turning off when you stop talking to them.

**Other Considerations**
None.

**Screenshots & Saves**
AT BIOA_PRO00 START_10_07

Before entering shed for the second time / After talking to Warren:
![image](https://user-images.githubusercontent.com/73685731/147580086-6b7c56f4-aabb-4014-9e99-d2ce7a701df1.png)

After entering shed for the second time / After talking to Manuel:
![image](https://user-images.githubusercontent.com/73685731/147580119-9863ce77-af1a-4602-8c95-3dc7ca35626a.png)

**Game file**
BIOA_PRO10_07_DSG.pcc
BIOA_PRO10_07_DSG_LOC_*.pcc

**Comment by henbagle** [comment]
Fixed in sequencing of BIOA_PRO10_07_DSG.pcc, in export 9168 Conversations sequence

Outlink to the light toggle (Export 8291) removed from Export 9090 and added to the "False" link of Export 848, so the light is only turned on by the FirstTimeSpeak trigger if you haven't had the initial conversation yet.

![image](https://user-images.githubusercontent.com/8151477/147691587-20424741-a45d-4bd1-8bfb-2a7bd5841428.png)
