### ISSUE TITLE
Prologue: Chakwas refuses to speak to you if you spam through her lines

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#120]
**Describe the bug**
When skipping through Chakwas' dialogue during the Prologue, she will no longer speak to you. Even Jenkins, who when talking to him would also initiate Chakwas' dialogue, will resort to using his unused "Sir" / "Ma'am" ambient dialogue.

**To Reproduce**
1. Start a new game
2. Talk to Chakwas
3. Quickly skip all her lines and end the conversation
4. Attempt to initiate a conversation with her again
5. If she talks, quickly skip all her lines and end the conversation again
6. If she doesn't talk, try talking to her via Jenkins

**Expected behavior**
Ability to talk to Chakwas as normal when approaching her again.

**Other Considerations**
Tested it on Pressley and he only exhibits a slight delay after his last ambient line before you can actually interact with him again but skipping any of his lines does not result in the inability to speak to him again so I assume that Chakwas is bugged.

**Screenshots & Saves**

https://user-images.githubusercontent.com/73685731/147652508-ed96d01a-c437-4bf1-b219-158ff89ac652.mp4

https://user-images.githubusercontent.com/73685731/147652600-30f0f9be-823a-4eba-a16d-ce58b87e7b01.mp4

**Game file**
BIOA_NOR10_03_DS1.pcc
BIOA_NOR10_03_DS1_LOC_*.pcc

**Comment by henbagle** [comment]
Fixed. BIOA_NOR10_03_DS1.pcc

Sequence export #7731 and #1109 swapped in order, so the transition that allows you to speak to Chakwas is now fired after the delay, instead of before. What was happening was you were being allowed to speak to Chakwas before she properly entered her actionstation, but the exit of the actionstation was what triggered the conversation. If she was not in her actionstation when you spoke to her, nothing would happen, the bool would be set so you could not speak to her, and you were stuck. This swap fixes it, but it means you have to wait .5 seconds before you can speak to her.

![image](https://github.com/henbagle/LE1CommunityPatch/assets/8151477/10251d3d-6315-4390-b5bd-4de564d1e59c)
