### ISSUE TITLE
Normandy: Hole in Liara's room

### ISSUE THREAD

**Issue by sialivi** [henbagle/LE1CommunityPatch#125]
**Describe the bug**
There's a hole in the geometry above the door in Liara's room when facing the Med Bay.

![Mass Effect Legendary Edition Screenshot 2022 03 13 - 01 55 52 39](https://user-images.githubusercontent.com/364734/158431808-d14691eb-c005-49cb-9e47-5a796a1b2ec8.jpg)

**Comment by henbagle** [comment]
File: BIOA_NOR10_08_LAY.pcc
Export: 43 NOR10_LABSUPPLY StaticMesh

Still investigating the process for properly replacing StaticMeshes in LE1 but when I figure it out this is on the list of things to fix.

**Comment by henbagle** [comment]
Fixed by adding a chunk of wall inside the existing wall in that level. Not the perfect solution, but mesh editing didn't work due to the pre-existing baked lighting. 
![image](https://user-images.githubusercontent.com/8151477/174507464-a0dc94ae-ddc3-4158-a6be-545a130696fc.png)

The following export added to BIOA_NOR10_08_LAY.pcc:
![image](https://user-images.githubusercontent.com/8151477/174507575-3db7da51-a57f-4f3d-8a90-9031bc1d941b.png)


(It looks kinda stupid if you fly outside the level)
![image](https://user-images.githubusercontent.com/8151477/174507481-6d4227ca-7e8f-42b0-b368-bc7622324b30.png)
