### ISSUE TITLE
Citadel: Calyn's first line of dialogue is cut off too early

### ISSUE THREAD

**Issue by sialivi** [henbagle/LE1CommunityPatch#127]
**Describe the bug**
When entering the Elcor & Volus embassy for the first time, elcor ambassador Calyn is having a conversation with Xeltan. The audio for Calyn's first line of dialogue abruptly cuts off too early.

> I understand what you are saying, but these allegations are very serious. I c~~an't just--~~

**Screenshots & Saves**
Video: https://www.youtube.com/watch?v=Vog_4qzX_QQ

**Comment by ShredzAlot** [comment]
I'm pretty that is intended to happen because he gets interrupted/cutoff by Xeltan.

**Comment by sialivi** [comment]
You're incorrect. The audio cuts off, with noticeable distortion, before it reaches Xeltans interruption. This bug seems to be unique to LE1, it plays fine in ME1.

**Comment by ShredzAlot** [comment]
Maybe it's unique to your game then cause it plays fine.
Take a look at this video
https://www.youtube.com/watch?v=r5s_SCGjxeM

**Comment by henbagle** [comment]
I've experienced this bug once or twice but it seems to be inconsistent, I can't get it to trigger all the time. Most of the time it doesn't happen. Nothing appears to be messed up about the dialogue node, it isn't intended to cut off at the point that it does. Preloading the conversation doesn't seem to fix it.

**Comment by henbagle** [comment]
Turns out this issue is a FemShep only issue! Huge thanks to Audemus for the fix.

BIOA_STA20_10D_DSG_LOC_INT.pcc. Other localizations will be checked for this issue on this line.

Animations totally cleared on FXA_75225 in sta20_trig_01_xeltancomplains_N.FXA_sta20_trig_01_xeltancomplains_sta20_elcor_ambassador_F. The animation for the same line in elcor_ambassador_M was exported to JSON, and reimported to replace the line in elcor_ambassador_F.

Something seems to be minorly borked with the FXA which is causing the line to skip. Reimporting the data from the male variant fixes the problem I guess.

![image](https://github.com/henbagle/LE1CommunityPatch/assets/8151477/016ed511-1d96-434d-86e0-210a67e9f848)

**Comment by henbagle** [comment]
Does not appear to be an issue in other localizations.
