### ISSUE TITLE
Kaidan incorrectly thinks the player is a Biotic

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#14]
**Describe the bug**
When speaking to Kaidan on the Normandy about his L2 implants he says that his L2 implants "spike higher than L3's" and then says "Except you, of course" which implies that Shepard is a biotic.

**Comment by mirh** [comment]
Is this actually a bug then?
Because I really couldn't remember this line, but many people on reddit seemed 300% sure even a soldier is a closeted biotic.

**Comment by d00telemental** [comment]
> Is this actually a bug then?
> Because I really couldn't remember this line, but many people on reddit seemed 300% sure even a soldier is a closeted biotic.

While I can't recall any codex entry that explicitly states that soldier/engineer/infiltrator Shepard has no biotic capabilities, I would argue that such Shepard being a biotic makes sense neither lore-wise (a) nor gameplay-wise (b).

a) Governments and militaries (except for asari) are shown to try to make most of any and all available servicemen showing even a hint of biotic talent - thus chances that a super-young SA military would just let Shepard roll "nah, I'ma pew-pew" are... handwavingly slim.

b) Having / not-having biotic implants is an in-game justification for playable class separation. ME1 allows players to upgrade / downgrade their "installed" biotic implant _only_ if they are of a biotic class - because it makes no sense for a person not exhibiting biotic abilities to have one.

What might be an interesting thing to try is checking if the otherwise non-biotic player has a biotic bonus power (barrier / stasis / warp / etc.) - because then it *would* make sense to consider a NG+ Shepard to have had some biotic training. However, I'm not sure that this kind of a check is a community patch material. Though I do believe that the basic fix should be included regardless.

**Comment by mirh** [comment]
The NG+ idea sounds actually pretty darn slick... but then there's just so much wrong and stupid with LE balancing..
Anyway, [this](https://old.reddit.com/r/masseffect/comments/20nmb9/how_strong_is_shepard/) is pretty much a list of whenever "cutscene [magic](https://tvtropes.org/pmwiki/pmwiki.php/Main/CutscenePowerToTheMax)" would make Shepard otherworldly powerful.

**Comment by henbagle** [comment]
Seems like the best we can probably do is skip that line, like so. Video incoming at some point.

![image](https://user-images.githubusercontent.com/8151477/126255779-da56258b-cefe-41e7-b7f4-4985ea7d58c4.png)

**Comment by henbagle** [comment]
Okay, currently if Shepard is biotic the line will play as normal, otherwise a version of the line without "Except you, of course" will play.

Video:
https://user-images.githubusercontent.com/8151477/126506251-95ddd691-c3f1-458d-9c16-55b9b6134772.mp4

**Comment by henbagle** [comment]
Some details on fix:
![image](https://user-images.githubusercontent.com/8151477/147415966-87c2708f-1a4b-4842-a24c-f0f1e0803407.png)
Node E365 and R473 duplicated to create a branching path in cha00_humanmale_kaidan_dlg in BIOA_NOR10_06kaidan_DSG_LOC_INT.pcc. Conditional 1374 added to make sure the original path is only taken if the player is a biotic. 

A new matinee has been setup for the new dialogue node (E444 in the image), with it's length set to 4.1 seconds. Shorting the length will cut off the line before the sentence we don't want to hear. A new TLK line has been added with the same line, but omitting the "Except for you, of course..." part. Gestures remain the same in the cloned matinee for the new line, but the BioEvtSysTrackVOElements points to the new TLK string.

![image](https://user-images.githubusercontent.com/8151477/147416049-e516d598-043c-4698-a2c8-380db3e32f55.png)

In order for this new line to play, the SoundCues for the original line have been cloned, both male and female, with the new TLK string ID in the export name. However, these two SoundCues reference the original SoundNodeWaves (export 6652 and 6653) for the original line, so the original audio is used. This allows us to have custom FaceFX and a new line in Dialogue Editor, while still leaving the original lines alone. 

![image](https://user-images.githubusercontent.com/8151477/147416122-4e9d08d1-3be5-4dcc-8a0d-6765d41af7e7.png)

These new sound cues are added to the ReferencedSoundCues array of both the Owner_M and Owner_F FaceFXAnimSets for the conversation, and the original FaceFX lines have been cloned. You can see that while the name for the new FaceFXLines matches the new TLK string ID, the Path and ID both reference the existing SoundNodeWave and SoundCue for the audio. This is required for the new line to point to the old audio. The cloned FaceFX lines, however, are used in the new dialogue path. The FaceFX has been edited to remove the lip synch movements leading into the deleted part of the line.
![image](https://user-images.githubusercontent.com/8151477/147416221-510bb527-3255-4bba-89fe-f07d7dc4d49f.png)

This fix has not been made to any VO dubs, as an understanding of the spoken language would be required to make this fix in an appropriate way.
