### ISSUE TITLE
Flux Stairs Loading Break

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#157]
**Describe the bug**
As you exit Flux and reach the end of the stairs leading into the upper wards, the game has to stop and load and render BIOA_STA60_02rail_DSG before continuing.

**To Reproduce**
Exit Flux and head into the Upper Wards via the stairs.

**Expected behavior**
BIOA_STA60_02rail already being loaded into memory by the BioTriggerStream prior to the one that renders it.

**Other Considerations**
None

**Screenshots & Saves**
"At BIOA_STA00 Start_STA60_03"

**Game file**
BIOA_STA00.pcc
Export 487 is the BioTriggerStream prior to the one that turns 02rail_DSG visible and lacks BIOA_STA60_02rail

**Comment by vegz** [comment]
I have the fix for this. TriggerStream_161 doesn't have BIOA_STA60_02rail loaded which causes the jump. Fixed by adding the file to the default streaming state and the steram_destiny streaming state.

![BOTH](https://user-images.githubusercontent.com/40906382/187533328-5f0be2b1-5217-48b1-a470-bb9d618d5ce8.png)

File: BIOA_STA00
