### ISSUE TITLE
Missing Citadel Tower Elevator Decal

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#158]
**Describe the bug**
The decal above the Citadel Tower Elevator in the presidium is missing.

**To Reproduce**
Stand infront of Citadel Tower Elevator in the Presidium

**Expected behavior**
A decal like in the original ME1

**Other Considerations**
None

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/187091150-ef0a93b3-05b3-459b-905f-24b72f6c0eb6.png)
![image](https://user-images.githubusercontent.com/73685731/187091273-9d48154d-4fc9-4434-b571-3068ae1742d6.png)

**Game file**
BIOA_STA20_(01?)

**Comment by henbagle** [comment]
Roughly fixed. BIOA_STA20_01_LAY.pcc

Properties and binary of export 184 updated with ME1 data to properly target the STA20_towerbase mesh. Previously it was targeting an incorrect mesh.

Exports 545 and 645 updated to enable actor collision, which enables the mesh to actually receive the decal. bCollideActors set to true on 545, CollideActors and bBioIsReceivingDecals set to true on 645.


![image](https://user-images.githubusercontent.com/8151477/188503119-8f054c4e-85a6-4415-96ba-550bf0baa357.png)

**Comment by CATACHR1SM** [comment]
![Screenshot 2022-11-10 032225](https://user-images.githubusercontent.com/27882475/201038576-1da99a34-4418-4361-afa0-29846ca2af69.jpg)
[BIOA_STA20_01_LAY.zip](https://github.com/henbagle/LE1CommunityPatch/files/9978783/BIOA_STA20_01_LAY.zip)

Fixed by correcting/adjusting UV's on mesh (un-mirroring that section) normals on flat surfaces should never mirror in the middle of a what's intended to be a flat face. seams up the arse if they do.
