### ISSUE TITLE
Normandy flies through trees on Eden Prime

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#159]
**Describe the bug**
During the Normandy's descent onto the play area, its right wing clips through a set of trees.

**To Reproduce**
Land on Eden Prime

**Expected behavior**
Normandy not flying through trees.

**Other Considerations**
None

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/187281085-26ff0fdc-ab66-4faa-9eb0-81a57ae341a5.png)
[Save_02.zip](https://github.com/henbagle/LE1CommunityPatch/files/9447407/Save_02.zip)

**Game file**
Trees are in BIOA_PRO10_00_LAY, Cutscene is in BIOA_PRO10_A_FLYBY_CIN

**Comment by CATACHR1SM** [comment]
![Treeclipissue](https://user-images.githubusercontent.com/27882475/201456629-78be08a7-a119-42b8-89fd-81b3c14c54eb.jpg)
[BIOA_PRO10_00_LAY.zip](https://github.com/henbagle/LE1CommunityPatch/files/9994068/BIOA_PRO10_00_LAY.zip)

Fixed edited the tree, scale was wrong x and y values were same number, when I match z to that, it worked. But also I had to pull tree down to ground, looks like LE devs use scale rather than position to fix a tree on the ground and it cause the issue because they didn't check Normandy scene.
