### ISSUE TITLE
Softlock before Saren bossfight on Virmire

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#163]
**Describe the bug**
If you talk to your squad when the Virmire..... casualty... at the AA tower speaks their last lines before Saren comes in, Saren's appearance is cancelled. This does not happen if you choose to go to the AA tower as there are no lines right before Saren's appearance.

**To Reproduce**
1. Choose to return to bombsite
2. Clear Bombsite
3. Talk to squadmates during last lines from the Virmire casualty

**Expected behavior**
Saren appears regardless of your interactions with the squad.

**Other Considerations**
None

**Screenshots & Saves**
[Alden00_136.zip](https://github.com/henbagle/LE1CommunityPatch/files/9471235/Alden00_136.zip)

**Game file**
Possibly BIOA_JUG80_07_DSG.pcc

**Comment by henbagle** [comment]
Fixed. BIOA_JUG80_07_DSG.pcc. In sequence Saren_Encounter_A, outlinks leading to new delay objects added to the four FOVOs for the Virmire casualty's lines. This way, if the lines fail or are aborted, the next line or the cutscene will be played after a short pause, rather than aborting the entire sequence. This allows time for the squadmate's banter to line to play and then the next thing in the sequence will occur.

![image](https://user-images.githubusercontent.com/8151477/188506091-08e739b3-ef94-40ec-a4e7-243596bca772.png)
