### ISSUE TITLE
Persistent Fast Travel Arrow

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#180]
**Describe the bug**
Basically right after being given free reign on the Citadel your given the option to fast travel. An arrow pointing to a fast travel point actually never goes away.

**To Reproduce**
Just walk by and it will pop up then fade away all the time.

**Screenshots & Saves**
![ScreenShot00007](https://user-images.githubusercontent.com/95461294/204195753-005d8db3-3cb1-41d3-80f3-37c5a972c26f.jpg)

https://user-images.githubusercontent.com/95461294/204195919-536ae4b6-e7b3-49e6-a19e-84a03ddbe1bd.mp4

**Comment by henbagle** [comment]
Fixed in roughly the same manner as #257 

![image](https://github.com/henbagle/LE1CommunityPatch/assets/8151477/41ddcbdd-f1b4-4b60-adb7-1509db871129)

New sequence object added so tutorial sequence doesn't play if tutorials are disabled.

![image](https://github.com/henbagle/LE1CommunityPatch/assets/8151477/93a006a9-5512-4b25-a937-a241ef892306)

This tutorial is also actually marked as completed so that players with tutorials enabled will no longer see the arrow when walking past.

**Comment by henbagle** [comment]
This fix doesn't seem to work when you have tutorials enabled and you reset them through the settings menu. Maybe the settings menu button isn't resetting the tutorial bool?

Very low priority but might be work taking a look at for a future update.
