### ISSUE TITLE
UNC: Major Kyle Biotic NPC Hand Placements

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#184]
**Describe the bug**
All biotic npc's hands are clipping with their weapons.  

**To Reproduce**
Persuade the dude at the door to let you in peacefully.

**Screenshots & Saves**
![ScreenShot00019](https://user-images.githubusercontent.com/95461294/204920566-bf19410c-13b0-45cf-995e-702c74e02803.jpg)
![ScreenShot00018](https://user-images.githubusercontent.com/95461294/204920581-d7801d29-f63a-4efa-a23f-ed3286afcaaf.jpg)
![ScreenShot00017](https://user-images.githubusercontent.com/95461294/204920603-d93bd2b9-e427-43c5-8d37-3df5654a7875.jpg)
![ScreenShot00016](https://user-images.githubusercontent.com/95461294/204920613-d777fa7e-28f9-4772-a4c6-3bc249d2f1c7.jpg)
![ScreenShot00015](https://user-images.githubusercontent.com/95461294/204920617-8aeb60f2-cab0-4029-9929-52f172a5bce1.jpg)

**Comment by henbagle** [comment]
File: BIOA_UNC54_02_DSG.pcc, BIOA_UNC54_03_DSG.pcc

Fixed by rondeeno

ISSUE: In UNC: Major Kyle, the biotic cultists' guns clip through their hands when you first enter the compound while they're non-hostile, which fixes itself if you save and reload or exit and reenter.
FIX: Added BioSeqAct_SetWeapon objects for each cultist to make sure none of their weapons are selected if they're not hostile.
