### ISSUE TITLE
Camera Bug with Dr. Michel

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#191]
**Describe the bug**
During her conversation with her blackmailer, one of the camera angle doesn't show the Doctor. 

Bug reported on LE1CP Mod Page

**Game file**
If possible, do you know which game file this bug is located in?

**Comment by vegz** [comment]
Fixed. 

File: BIOA_STA60_08A_DSG_LOC_INT
Will require being done for all LOCs though.

The interpmove X value is too far to the left, it is fixed by changing the x value in the InterpTrackMove in the Cam InterpGroup from -10268.69 to -10305.6

![LE1](https://user-images.githubusercontent.com/40906382/220382215-21f95125-b467-4d12-b819-7bda3ef0d343.PNG)
9.

![Mass Effect 2_21_2023 9_31_52 AM](https://user-images.githubusercontent.com/40906382/220382233-abc5da65-d290-461d-9d0c-556f2fc8bd7b.png)

![Mass Effect 2_21_2023 9_38_05 AM](https://user-images.githubusercontent.com/40906382/220382241-69cbc864-c7b3-4c6d-8c18-07c8bf6c2736.png)
