### ISSUE TITLE
Nassana Dantius charm/intimidate Armali Council License (bool 7161 not checked)

### ISSUE THREAD

**Issue by mechcentric** [henbagle/LE1CommunityPatch#194]
bool number 7161 not checked after charming (possibly intimidating) nassana dantius to obtain armali council license. able to purchase license from commander rentola.

**Comment by henbagle** [comment]
Charming/intimidating Nassana actually sets it's own bool in the game (7099), but it is never checked again, so it's functionally useless. Updated transition 5782 (SP108_SlaverQueen.Set_extra_reward_true) so it also sets 7161 to true, giving the player the Armali council license. 

![image](https://user-images.githubusercontent.com/8151477/213968755-1fb4d687-56d0-402b-be4f-ba060b2b9c6d.png)

**Comment by henbagle** [comment]
There's actually nothing in game as far as I can tell that says that you should get the Armali License from this outcome. It's just the Mass Effect Wiki that says so (and then in game it does nothing). This seems like a pretty reasonable outcome though.

**Comment by henbagle** [comment]
Okay, a longstanding issue that I have actually never noticed before has cropped up. Unfortunately we are not able to override basegame transitions for some reason. To fix this, I moved my changed transition 5782 to be a new transition, 6603. Conversation sp108_diplomat_dlg in BIOA_STA20_09A_DSG_LOC_INT (and all localizations) updated so that E54 and E55 point to transition 6603.

![image](https://user-images.githubusercontent.com/8151477/217306261-f1cdaf38-37b8-431d-8bc4-14b6c0d62a47.png)
