### ISSUE TITLE
Floating Grass In Citadel Tower

### ISSUE THREAD

**Issue by Mike7099** [henbagle/LE1CommunityPatch#255]
There are some patches of grass in the gardens of the Citadel Tower that are clearly floating in mid-air due to bad placement.

Images:

![grass](https://github.com/henbagle/LE1CommunityPatch/assets/107361119/b91bea0c-956e-4d2e-b705-702ff4287335)

**Comment by henbagle** [comment]
The entirety of the grass for this portion of the map is all one giant mesh that's merged together. I've written down which grass pieces need to move and by how much, but actually editing it will be tricky. 

I'm gonna have to get blender out to fix this, and I am not very good at blender. Might not be fixed in the next update. Thanks for the report!

**Comment by henbagle** [comment]
I have braved the dangers of mesh modding and come out victorious! This is fixed and will be included in 1.7.2. I don't have any screenshots because I forgot to take them. 

Mesh edited is STA70_GRASS34_B in BIOA_STA70_02_LAY_DSG.pcc. This is the only instance of the mesh in the game so I have just updated the mesh in place.
