### ISSUE TITLE
Object Pop-in / Pop-out on Eden Prime

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#34]
**Describe the bug**
When approaching the cutscene trigger that shows Saren killing Nihlus, the fires, smoke and some shrubbery dissapear or appear in plain sight of the player.

**To Reproduce**
In Console: "At BIOA_PRO00 Start_PRO10_07"
Move back and forward infront of the Cutscene Trigger that shows Saren killing Nihlus while looking at the objects above the cliff.

**Expected behavior**
The pop-in / pop-out should not be visible to the player.

**Other Considerations**
None

**Screenshots & Saves**
Before: 
![image](https://user-images.githubusercontent.com/73685731/126065564-3097a250-e101-41a1-92ff-5fde97eecaf9.png)

After:
![image](https://user-images.githubusercontent.com/73685731/126065591-6906467b-c907-4921-be0b-9a5a6a3d0446.png)

**Game file**
One of the BIOA_PRO10_07 files

**Comment by henbagle** [comment]
I have a partial fix for this. Exports 240, 246, and 249 and their trees have been cloned into BIOA_PRO10_00_LAY.pcc and removed from BIOA_PRO10_05_LAY.pcc. These three exports are the emitters for the three smoke effects that can pop out. I've left the shrubbery for the moment because it's not super noticeable like the smoke is
