### ISSUE TITLE
Squad Banter about Anderson cutting out as you leave Choras Den

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#35]
**Describe the bug**
After you talk to Harkin and he reveals Captain Andersons past, the squad comments about it as you exit Choras Den. However, at a certain distance this dialogue is cut off before it can finish.

**To Reproduce**
1. In Console: "At BIOA_STA00 Start_STA60_05"
2. In Console: "ce hench_picksquad" and select Kaiden and Ashley.
3. Talk to Harkin so that he reveals Andersons past
4. Walk out of Choras Den and go straight to the rapid transit terminal

**Expected behavior**
The dialogue should not be cut off.

**Other Considerations**
None

**Screenshots & Saves**
None

**Game file**
Either BIOA_STA60_04 or BIOA_STA60_05

**Comment by henbagle** [comment]
The issue is that BIOA_STA60_05A, the file containing the banter, is streamed out between Chora's Den and the rapid transit terminal, so the playing conversation is no longer in memory and gets cut out.

To fix the issue, the BioConversation for this banter, including all referenced TLK files, FaceFX, interps, and audio, have all been copied from BIOA_STA60_05A_DSG_LOC_INT to BIOA_STA60_04_DSG_LOC_INT. This will require fixing on all localizations. 
In order to trigger this conversation, the BioTriggerVolume, imports, and sequencing/plot checks to trigger the ambient need to be copied from BIOA_STA60_05A_DSG to BIOA_STA60_04_DSG, as for some reason the game cannot find the BioConversation in it's new location. (The fix for #36 came with it). The original sequencing has been disconnected.

![image](https://user-images.githubusercontent.com/8151477/130338642-6c06ea6d-baba-45e5-b1dc-4d294a13d744.png)
Original sequencing disconnected in BIOA_STA60_05A_DSG.pcc, in sequence 10565

![image](https://user-images.githubusercontent.com/8151477/130338651-9d9a30cb-8f88-4986-89f1-885a002f1e9e.png)
New sequencing in BIOA_STA60_04_DSG.pcc

![image](https://user-images.githubusercontent.com/8151477/130338670-aa3ebb11-8a87-4f00-bb91-d34eb4aa781b.png)
Dialogue ported to BIOA_STA60_04_DSG_LOC_INT.pcc
