### ISSUE TITLE
Conversation overlap at Choras Den

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#36]
**Describe the bug**
When doing the Rita's Sister sidequest and after having talked to both Harkin and Jenna you get an overlap of the ambient squad banter about Andersons past and the interaction between Chellick and Shepard.

**To Reproduce**
1. Talk to Rita and start her sidequest
2. Go to Choras Den and talk to Jenna
3. Talk to Harkin until he reveals Andersons past
4. Walk out of Choras Den

**Expected behavior**
The trigger for the squad banter should be moved beyond the Choras Den doorway.

**Other Considerations**
None

**Screenshots & Saves**
[LE1CP-Issue36.zip](https://github.com/henbagle/LE1CommunityPatch/files/6836326/LE1CP-Issue36.zip)

**Game file**
Either BIOA_STA60_04 or BIOA_STA60_05

**Comment by henbagle** [comment]
Super easy to move the trigger volume beyond the doorway, but it increases the chances of the conversation getting cut off when the file streams out (which is midway through the bit where you fight the assassins). The conversation can get cut off in this way in vanilla, but it just happens earlier with this fix, because the ambient starts later.

Working on a fix.

Files: BIOA_STA60_05A_DSG.pcc, BIOA_STA60_04_DSG.pcc,

**Comment by henbagle** [comment]
Fixed. Y value of the location of the BioTriggerVolume changed to -5325 from around -5500. Export 2791 in BIOA_STA60_05A_DSG.pcc. I don't think the streaming thing will be a huge issue as it is a vanilla bug, but if there is an easy way to fix it I will try.

Also fixed the first line of Chellick's conversation (where he bumps into and whispers a line to Shepard) not being properly in cinematic mode, so the player could use enter command mode or access the main menu. Added ToggleCinematicMode sequence objects around the interp for this line, as shown below. Same file, export 10561
![image](https://user-images.githubusercontent.com/8151477/130329571-96cb9392-f106-453a-911a-e20a1ab0e7d7.png)
