### ISSUE TITLE
Unable to interact with Thorium Deposit on Nepheron

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#37]
**Describe the bug**
On the planet nepheron in the columbia system (voyager cluster), there is an ore called thorium deposit you are unable to interact with it with either keyboard nor controller 

**Expected behavior**
Ore should trigger the minigame and add to your quest

**Screenshots & Saves**

https://user-images.githubusercontent.com/8151477/126070827-c3fd0281-4455-4419-acec-c05fc2a5670f.mp4

[John00_13 - dragonbor 166.zip](https://github.com/henbagle/LE1CommunityPatch/files/6836412/John00_13.-.dragonbor.166.zip)

**Comment by d00telemental** [comment]
Just checked using the attached save - the minigame shows up fine with keyboard / mouse.

I think it is a part of a broader issue where all POI interactions would stop working for an unknown reason. Interestingly enough, [June 7 patchnotes](https://www.ea.com/games/mass-effect/mass-effect-legendary-edition/news/update-6-7) seem to indicate that this bug was fixed:

> Fixed an issue that would prevent the ability to interact with objects

Apparently it wasn't?

**Comment by henbagle** [comment]
This bug report may have been submitted before the patch, most issues in this repo come from the bug hunt initiatives.

**Comment by henbagle** [comment]
Closed: Save has been tested without issue on both keyboard and gamepad, bug believed to be fixed in the June 7th patch.
