### ISSUE TITLE
Citadel: Rita's Sister can end prematurely

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#45]
**Describe the bug**
During the mission Citadel: Rita's Sister, you can end the mission prematurely by speaking to Rita in certain situations when there are still mission steps left to complete.

**To Reproduce**
If you persuade Chellick to let Jenna go, but then agree to help him get the mods from Jax, the mission will not be complete, as there are more things to do. At this point, if you speak to Rita, before or after getting the mods from Jax, the mission will be marked as complete in the journal.

**Expected behavior**
The mission should not be complete until you have resolved the scenario with Jax.

**Other Considerations**
This was a bug in ME1 as well, and was fixed by ME1Recalibrated.

**Comment by AudemusN7** [comment]
My proposed solution to this issue would be to split the mission into two. The task to get the mods from Jax can be an entirely new quest called _Citadel: Arms Deal_. This would disentangle the tasks effectively and make it so that speaking to Jenna is the end to the Rita's Sister mission, and speaking to Chellick after dealing with Jax is the end of the Arms Deal mission.

The downside to this is that it is quite an aggressive change and may cause confusion with users that use official guides and walkthroughs.

**Comment by henbagle** [comment]
Thanks to Rondeeno for the fix.

Transition 2206 (quest marked as complete) has been removed from Rita's dialogue. All of the outcomes with Chellick include this transition, so the quest will be marked as complete anyway, no matter how the quest goes.

**File:** BIOA_STA60_09A_DSG_LOC_INT.pcc

![image](https://user-images.githubusercontent.com/8151477/130638589-1ea68f48-66f0-4784-8eb2-87095d9a048e.png)
